In [15]:
import pandas as pd

weighthistory_df = pd.read_sas("WeightHistory_2017_18.xpt")
foodsecurity_df = pd.read_sas("FoodSecurity_2017_18.xpt")
smokinghist_df = pd.read_sas("SmokingHistory_CigUse_2017_18.xpt")
secondhandsmoke_df = pd.read_sas("SmokingHistorySecondHand_2017_18.xpt")
rxdrugs_df = pd.read_sas("PrescriptionDrugs_2017_18.xpt")
druguse_df = pd.read_sas("DrugUse_2017_18.xpt")
nicotinemetabolites = pd.read_sas("NicotineMetabolites_2017_18.xpt")
hdl_df = pd.read_sas("CholesterolHDL_2017_18.xpt")
ldl_trig_df = pd.read_sas("CholesterolLDL_2017_18.xpt")


nicotinebysmoke_df = smokinghist_df.merge(right=nicotinemetabolites, how="inner", on="SEQN")

print(nicotinebysmoke_df)

          SEQN  SMQ020  SMD030  SMQ040  SMQ050Q  SMQ050U  SMD057  SMQ078  \
0      93707.0     NaN     NaN     NaN      NaN      NaN     NaN     NaN
1      93708.0     2.0     NaN     NaN      NaN      NaN     NaN     NaN
2      93711.0     2.0     NaN     NaN      NaN      NaN     NaN     NaN
3      93712.0     1.0    17.0     2.0      NaN      NaN     NaN     NaN
4      93714.0     1.0    15.0     3.0     20.0      4.0     5.0     NaN
...        ...     ...     ...     ...      ...      ...     ...     ...
2126  102946.0     2.0     NaN     NaN      NaN      NaN     NaN     NaN
2127  102947.0     1.0    19.0     3.0     35.0      4.0     5.0     NaN
2128  102948.0     1.0    17.0     3.0      7.0      4.0     1.0     NaN
2129  102949.0     1.0    18.0     1.0      NaN      NaN     NaN     1.0
2130  102956.0     1.0    16.0     1.0      NaN      NaN     NaN     2.0

      SMD641  SMD650  ...  URXNICT      URDNICLC URXNNCT      URDNCTLC  \
0        NaN     NaN  ...      NaN  2.000000e+00     NaN  2.000000e+00
1        NaN     NaN  ...      NaN  2.000000e+00     NaN  2.000000e+00
2        NaN     NaN  ...      NaN  2.000000e+00     NaN  2.000000e+00
3        5.0     2.0  ...     7.42  1.000000e+00    1.77  1.000000e+00
4        NaN     NaN  ...      NaN  2.000000e+00     NaN  2.000000e+00
...      ...     ...  ...      ...           ...     ...           ...
2126     NaN     NaN  ...      NaN  2.000000e+00     NaN  2.000000e+00
2127     NaN     NaN  ...      NaN  2.000000e+00     NaN  2.000000e+00
2128     NaN     NaN  ...      NaN  2.000000e+00     NaN  2.000000e+00
2129    30.0    20.0  ...  3690.00  5.397605e-79  157.00  5.397605e-79
2130    30.0    20.0  ...   787.00  5.397605e-79   72.60  5.397605e-79

      URXNOXT      URDNOXLC    URDTNE2  URDTNE3  URDTNE6  URDTNE7
0         NaN  2.000000e+00   0.131800      NaN      NaN      NaN
1         NaN  2.000000e+00   0.001509      NaN      NaN      NaN
2         NaN  2.000000e+00   0.010030      NaN      NaN      NaN
3        1.77  1.000000e+00   0.439800   0.4855   0.5206    0.526
4         NaN  2.000000e+00   0.019900      NaN      NaN      NaN
...       ...           ...        ...      ...      ...      ...
2126      NaN  2.000000e+00   0.025330      NaN      NaN      NaN
2127      NaN  2.000000e+00   0.001130      NaN      NaN      NaN
2128      NaN  2.000000e+00   0.001650      NaN      NaN      NaN
2129   849.00  5.397605e-79  34.610000  57.3500  66.9900   72.070
2130   368.00  5.397605e-79  47.070000  51.9200  56.9000   59.060

[2131 rows x 60 columns]

Notes:

Questionnaire data from : https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire&CycleBeginYear=2017

*Nicotine by Smoking History variable names:*

Questionnaire:
* SMD030 - Age started smoking cigarettes regularly
* SMD641 - # days smoked cigs during past 30 days
* SMQ078 - How soon after waking do you smoke
* SMQ050Q - How long since quit smoking cigarettes

*Lab*
* URXCOTT - Cotinine, urine (ng/mL)
* URXNNCT - Nornicotine, urine (ng/mL)

In [16]:
#print(nicotinebysmoke_df[["SMD030", "SMD641", "URXCOTT", "URXNNCT"]])

nicotinebysmoke_df[["SMD030", "SMD641", "SMQ050Q", "SMQ078", "URXCOTT", "URXNNCT"]].corr()

           SMD030    SMD641   SMQ050Q    SMQ078   URXCOTT   URXNNCT
SMD030   1.000000  0.025187  0.217885  0.002814 -0.034098 -0.035898
SMD641   0.025187  1.000000       NaN -0.071694  0.210681  0.241940
SMQ050Q  0.217885       NaN  1.000000       NaN  0.009650  0.025625
SMQ078   0.002814 -0.071694       NaN  1.000000 -0.085705 -0.090929
URXCOTT -0.034098  0.210681  0.009650 -0.085705  1.000000  0.840649
URXNNCT -0.035898  0.241940  0.025625 -0.090929  0.840649  1.000000

Number of days where one smoked in the past month were about 20% correlated with cotinine and nornicotine levels.